apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - app-configmap.yaml
  - app-consumer-deployment.yaml
  - app-deployment.yaml
  - app-hpa.yaml
  - app-ingress.yaml
  - app-service.yaml
  - app-vpa.yaml
